"""BioClaw-style notebook export — auto-generate reproducible .ipynb from agent sessions."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional


def export_session_to_notebook(
    session_id: str,
    messages: List[Dict[str, Any]],
    events: List[Dict[str, Any]],
    output_dir: Path,
    title: Optional[str] = None,
) -> Path:
    """Export an AI session to a Jupyter notebook for reproducibility.

    BioClaw-inspired: every agent run auto-generates a .ipynb file with
    the full conversation, tool calls, and results.
    """
    cells: List[Dict[str, Any]] = []

    # Title cell
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            f"# {title or 'MitoFlow AI Session'}\n",
            f"\n",
            f"Session ID: `{session_id}`\n",
            f"\n",
            f"*Auto-generated by MitoFlow AI — reproduce or continue analysis below.*\n",
        ],
    })

    # Conversation cells
    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")

        if role == "system":
            # Skip verbose system prompts — include as collapsed markdown
            short_content = content[:200] + "..." if len(content) > 200 else content
            cells.append({
                "cell_type": "markdown",
                "metadata": {"tags": ["system_prompt"]},
                "source": [f"<details><summary>System Prompt</summary>\n\n```\n{short_content}\n```\n</details>\n"],
            })

        elif role == "user":
            cells.append({
                "cell_type": "markdown",
                "metadata": {"tags": ["user_query"]},
                "source": [f"### Query\n\n{content}\n"],
            })

        elif role == "assistant":
            tool_calls = msg.get("tool_calls", [])
            source_lines = [f"### Response\n\n{content}\n"]
            if tool_calls:
                source_lines.append("\n**Tools called:** " + ", ".join(
                    tc.get("name", "?") for tc in tool_calls
                ) + "\n")
            cells.append({
                "cell_type": "markdown",
                "metadata": {"tags": ["agent_response"]},
                "source": source_lines,
            })

        elif role == "tool":
            name = msg.get("name", "unknown")
            cells.append({
                "cell_type": "code",
                "metadata": {"tags": ["tool_output"]},
                "source": [f"# Tool: {name}\n", f"# Result:\n{content[:500]}\n"],
                "outputs": [],
            })

    # Event summary
    if events:
        tool_events = [e for e in events if e.get("type") in ("tool_call", "tool_result")]
        if tool_events:
            event_summary = "\n".join(
                f"- [{e['type']}] {e.get('message', '')[:80]}"
                for e in tool_events
            )
            cells.append({
                "cell_type": "markdown",
                "metadata": {"tags": ["event_log"]},
                "source": [f"### Event Log\n\n{event_summary}\n"],
            })

    # Reproducibility footer
    cells.append({
        "cell_type": "code",
        "metadata": {"tags": ["reproducibility"]},
        "source": [
            "# MitoFlow AI — Reproducibility Cell\n",
            "# Re-run the analysis below:\n",
            "from mitoflow.ai.service import AIService, build_default_registry\n",
            f"# session_id = '{session_id}'\n",
            "# svc = AIService(...)\n",
            "# result = svc.send_message(session_id, 'your query', EntryPoint.CLI)\n",
        ],
        "outputs": [],
    })

    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (MitoFlow)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0",
            },
        },
        "cells": cells,
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    nb_path = output_dir / f"{session_id}.ipynb"
    nb_path.write_text(json.dumps(notebook, indent=1, ensure_ascii=False), encoding="utf-8")
    return nb_path
